# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://vayudesigns.com
title: Vāyu
email: admin@vayudesigns.com
author: Justin Lewis
description: Packs that bring you from work to adventure.
copyright: 'Copyright &copy; 2018 Vāyu. All Rights Reserved.'
credits:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  # - title: facebook
  #   url: https://www.facebook.com/vayudesigns
  - title: instagram
    icon: instagram
    url: https://www.instagram.com/vayudesigns
